-- Sample tours for LOCAL TESTS ONLY (invented content). Load after db/seed.sql. Do not run this on the real database.
PRAGMA foreign_keys = ON;

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (1, 'theth', 12, 95, NULL, 1, 1, 1, 'mountain', 3);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (1, 'en', 'theth', 'Theth Valley & Grunas Waterfall', 'Over the Albanian Alps by road, then a gentle walk to the Grunas waterfall and the Blue Eye of Theth.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (1, 1);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (1, 1, 1, '07:30');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (1, 'en', 'Pickup in Tirana or Shkodër');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (2, 1, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (2, 'en', 'Mountain road to Theth with photo stops');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (3, 1, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (3, 'en', 'Walk to Grunas waterfall & the stone church');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (4, 1, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (4, 'en', 'Lunch in a family guesthouse');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (5, 1, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (5, 'en', 'Back by 19:30');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (1, 1, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (1, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (2, 1, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (2, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (3, 1, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (3, 'en', 'Lunch at a guesthouse');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (4, 1, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (4, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 1, 'en', 'Theth Valley & Grunas Waterfall | Escape to Albania', 'Over the Albanian Alps by road, then a gentle walk to the Grunas waterfall and the Blue Eye of Theth.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (2, 'koman', 11, 90, NULL, 1, 0, 2, 'lake', 5);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (2, 'en', 'koman', 'Lake Koman & Valbona Ferry', 'Three hours on a ferry between sheer cliffs: one of the most beautiful boat rides in Europe.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (2, 1);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (6, 2, 1, '06:30');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (6, 'en', 'Early start from Tirana');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (7, 2, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (7, 'en', 'Drive to Koman through Mirdita');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (8, 2, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (8, 'en', 'Ferry through the fjord-like gorge');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (9, 2, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (9, 'en', 'Swim and lunch at the lake');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (10, 2, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (10, 'en', 'Return by evening');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (5, 2, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (5, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (6, 2, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (6, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (7, 2, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (7, 'en', 'Ferry ticket');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (8, 2, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (8, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 2, 'en', 'Lake Koman & Valbona Ferry | Escape to Albania', 'Three hours on a ferry between sheer cliffs: one of the most beautiful boat rides in Europe.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (3, 'shkoder', 9, 65, NULL, 1, 0, 3, 'lake', 9);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (3, 'en', 'shkoder', 'Shkodër, Rozafa & the Lake', 'The old Catholic heart of Albania: Rozafa castle, Marubi photo museum and a sunset over the lake.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (3, 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (3, 2);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (11, 3, 1, '09:00');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (11, 'en', 'Pickup in Tirana');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (12, 3, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (12, 'en', 'Rozafa castle and its legend');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (13, 3, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (13, 'en', 'Marubi National Museum of Photography');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (14, 3, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (14, 'en', 'Fish lunch at Lake Shkodër');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (15, 3, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (15, 'en', 'Sunset at Shiroka');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (9, 3, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (9, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (10, 3, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (10, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (11, 3, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (11, 'en', 'Castle entrance');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (12, 3, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (12, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 3, 'en', 'Shkodër, Rozafa & the Lake | Escape to Albania', 'The old Catholic heart of Albania: Rozafa castle, Marubi photo museum and a sunset over the lake.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (4, 'tirana', 6, 55, NULL, 1, 0, 4, 'city', 2);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (4, 'en', 'tirana', 'Tirana Food & Bunk’Art Walk', 'The capital through its kitchens and its history: byrek at dawn, Blloku, the Pyramid and the bunker museum.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (4, 4);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (4, 2);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (16, 4, 1, '10:00');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (16, 'en', 'Meet at Skanderbeg Square');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (17, 4, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (17, 'en', 'Old bazaar & Et’hem Bey mosque');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (18, 4, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (18, 'en', 'Tasting stops: byrek, qofte, raki');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (19, 4, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (19, 'en', 'Bunk’Art 1 museum');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (20, 4, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (20, 'en', 'Coffee in Blloku');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (13, 4, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (13, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (14, 4, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (14, 'en', 'All food tastings');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (15, 4, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (15, 'en', 'Museum entrance');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (16, 4, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (16, 'en', 'Walking route map');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 4, 'en', 'Tirana Food & Bunk’Art Walk | Escape to Albania', 'The capital through its kitchens and its history: byrek at dawn, Blloku, the Pyramid and the bunker museum.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (5, 'berat', 10, 75, NULL, 1, 1, 5, 'castle', 4);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (5, 'en', 'berat', 'Berat, the City of a Thousand Windows', 'A UNESCO town of white Ottoman houses stacked up a hillside, with a living castle on top.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (5, 2);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (21, 5, 1, '08:30');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (21, 'en', 'Pickup in Tirana');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (22, 5, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (22, 'en', 'Berat castle & Onufri museum');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (23, 5, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (23, 'en', 'Walk across the Gorica bridge');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (24, 5, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (24, 'en', 'Lunch with a view over Mangalem');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (25, 5, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (25, 'en', 'Wine tasting at a family cellar');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (17, 5, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (17, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (18, 5, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (18, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (19, 5, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (19, 'en', 'Wine tasting');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (20, 5, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (20, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 5, 'en', 'Berat, the City of a Thousand Windows | Escape to Albania', 'A UNESCO town of white Ottoman houses stacked up a hillside, with a living castle on top.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (6, 'gjirokaster', 13, 85, NULL, 1, 0, 6, 'castle', 7);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (6, 'en', 'gjirokaster', 'Gjirokastër & the Blue Eye', 'The stone city and its fortress, then a swim at the cold, impossibly blue spring of Syri i Kaltër.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (6, 2);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (6, 3);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (26, 6, 1, '07:00');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (26, 'en', 'Start from Tirana');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (27, 6, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (27, 'en', 'Gjirokastër bazaar & Zekate house');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (28, 6, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (28, 'en', 'Castle & the Cold War tunnel');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (29, 6, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (29, 'en', 'Lunch in a stone house');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (30, 6, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (30, 'en', 'The Blue Eye spring');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (21, 6, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (21, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (22, 6, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (22, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (23, 6, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (23, 'en', 'Castle entrance');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (24, 6, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (24, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 6, 'en', 'Gjirokastër & the Blue Eye | Escape to Albania', 'The stone city and its fortress, then a swim at the cold, impossibly blue spring of Syri i Kaltër.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (7, 'ksamil', 11, 85, NULL, 1, 1, 7, 'coast', 6);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (7, 'en', 'ksamil', 'Ksamil & Butrint', 'Ancient Butrint in the morning, turquoise water at Ksamil in the afternoon, grilled fish in between.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (7, 3);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (7, 2);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (31, 7, 1, '07:30');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (31, 'en', 'Pickup from Sarandë or Tirana');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (32, 7, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (32, 'en', 'Butrint archaeological park');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (33, 7, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (33, 'en', 'Ksamil beach & boat to the islets');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (34, 7, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (34, 'en', 'Seafood lunch');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (35, 7, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (35, 'en', 'Sunset on the Sarandë promenade');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (25, 7, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (25, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (26, 7, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (26, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (27, 7, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (27, 'en', 'Butrint entrance');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (28, 7, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (28, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 7, 'en', 'Ksamil & Butrint | Escape to Albania', 'Ancient Butrint in the morning, turquoise water at Ksamil in the afternoon, grilled fish in between.', '', 0);

INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES (8, 'llogara', 11, 80, NULL, 1, 0, 8, 'road', 8);
INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES (8, 'en', 'llogara', 'Llogara Pass & Himara Riviera', 'Pine forests at 1,000 m, then switchbacks down to the Ionian Sea and the quiet beaches of Dhërmi and Himara.', 1);
INSERT INTO tour_tags (tour_id, tag_id) VALUES (8, 3);
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (36, 8, 1, '08:00');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (36, 'en', 'Pickup in Vlorë');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (37, 8, 2, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (37, 'en', 'Llogara national park viewpoint');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (38, 8, 3, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (38, 'en', 'Dhërmi old village');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (39, 8, 4, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (39, 'en', 'Swim at Gjipe or Livadhi');
INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES (40, 8, 5, '');
INSERT INTO tour_step_i18n (step_id, lang, text) VALUES (40, 'en', 'Taverna lunch in Himara');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (29, 8, 1);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (29, 'en', 'Private vehicle & fuel');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (30, 8, 2);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (30, 'en', 'Local guide');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (31, 8, 3);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (31, 'en', 'Beach stops');
INSERT INTO tour_included (id, tour_id, sort_order) VALUES (32, 8, 4);
INSERT INTO tour_included_i18n (included_id, lang, text) VALUES (32, 'en', 'Hotel pickup');
INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES ('tour', 8, 'en', 'Llogara Pass & Himara Riviera | Escape to Albania', 'Pine forests at 1,000 m, then switchbacks down to the Ionian Sea and the quiet beaches of Dhërmi and Himara.', '', 0);

