"""Builds db/seed.sql from public/data/tours.json (English text; Albanian is added later in the admin).

  python tools/make_seed.py            # writes db/seed.sql
Run it once on an empty database, after the migrations:
  npx wrangler d1 execute escape-to-albania --remote --file db/seed.sql
"""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
tours = json.load(open(os.path.join(ROOT, 'public/data/tours.json'), encoding='utf-8'))
out = ['-- Generated by tools/make_seed.py. Safe to run once on an empty database.', 'PRAGMA foreign_keys = ON;', '']
q = lambda v: 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
n = lambda v: 'NULL' if v in (None, '') else str(int(float(v)))

REGIONS = {'north': ('North', 'Veri'), 'culture': ('Culture', 'Kulturë'), 'coast': ('Coast', 'Bregdet'), 'city': ('City', 'Qyteti')}
for i, (key, (en, sq)) in enumerate(REGIONS.items(), 1):
    out += [f"INSERT INTO tags (id, kind, key) VALUES ({i}, 'region', {q(key)});",
            f"INSERT INTO tag_i18n (tag_id, lang, name) VALUES ({i}, 'en', {q(en)}), ({i}, 'sq', {q(sq)});"]
tag_id = {k: i for i, k in enumerate(REGIONS, 1)}

out += ['', '-- Static pages']
for i, key in enumerate(['home', 'tours', 'about', 'journal', 'contact'], 1):
    out.append(f"INSERT INTO pages (id, key) VALUES ({i}, {q(key)});")

out += ['', '-- Settings (fill in from the admin)']
for k, v in [('contact_email', ''), ('contact_whatsapp', ''), ('contact_instagram', ''), ('notify_emails', ''),
             ('seo_title_pattern', '%title% | Escape to Albania'), ('ga4_property_id', ''), ('search_console_domain', '')]:
    out.append(f"INSERT INTO settings (key, value) VALUES ({q(k)}, {q(v)});")

out += ['', '-- Tours']
step_id = incl_id = 0
for ti, t in enumerate(tours, 1):
    out += [f"INSERT INTO tours (id, key, hours, price_from, max_guests, published, featured, sort_order, scene, seed) VALUES "
            f"({ti}, {q(t['slug'])}, {n(t.get('hours'))}, {n(t.get('price'))}, {n(t.get('max') or 4)}, {1 if t.get('published', True) else 0}, {1 if t.get('featured') else 0}, {ti}, {q(t.get('scene'))}, {n(t.get('seed'))});",
            f"INSERT INTO tour_i18n (tour_id, lang, slug, title, short, ready) VALUES ({ti}, 'en', {q(t['slug'])}, {q(t['title'])}, {q(t.get('short', ''))}, 1);"]
    for tag in str(t.get('tags', '')).split():
        if tag in tag_id:
            out.append(f"INSERT INTO tour_tags (tour_id, tag_id) VALUES ({ti}, {tag_id[tag]});")
    for si, s in enumerate(t.get('steps', []), 1):
        step_id += 1
        out += [f"INSERT INTO tour_steps (id, tour_id, sort_order, time) VALUES ({step_id}, {ti}, {si}, {q(s.get('t', ''))});",
                f"INSERT INTO tour_step_i18n (step_id, lang, text) VALUES ({step_id}, 'en', {q(s.get('s', ''))});"]
    for ii, text in enumerate(t.get('incl', []), 1):
        incl_id += 1
        out += [f"INSERT INTO tour_included (id, tour_id, sort_order) VALUES ({incl_id}, {ti}, {ii});",
                f"INSERT INTO tour_included_i18n (included_id, lang, text) VALUES ({incl_id}, 'en', {q(text)});"]
    seo = t.get('seo') or {}
    out.append(f"INSERT INTO seo (owner_type, owner_id, lang, title, description, focus_keyword, noindex) VALUES "
               f"('tour', {ti}, 'en', {q(seo.get('title', ''))}, {q(seo.get('desc', ''))}, {q(seo.get('keyword', ''))}, {1 if seo.get('noindex') else 0});")
    out.append('')

open(os.path.join(ROOT, 'db/seed.sql'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('wrote db/seed.sql:', len(tours), 'tours')
